# Generated by Django 5.2.2 on 2025-06-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golo',
            name='minuto',
        ),
        migrations.AddField(
            model_name='golo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
